### PR TITLE
Added introslider and onboarding for new users

### LINKED ISSUE #89: Adding an Intro Slider to the application for new users
**Is your feature request related to a problem? Please describe.**
The app doesn't have a proper intro-slider set up. If done, it would make the users get familiar with the application fairly easily and would make them understand how to use the application properly.

**Describe the solution you'd like**
I'd design and implement the intro screens along with proper onboarding, so that when the app would be installed and opened for the first time, the users would be greeted by an automated experience which would acquaint users with app's features and how to use it.

**Sample intro and onboarding screens for the purpose of understanding and clarity**

68747470733a2f2f75706c616e64736f6674776172652e636f6d2f6c6f63616c79746963732f77702d636f6e74656e742f75706c6f6164732f73697465732f34352f323032302f30362f6170702d757365722d6f6e626f617264696e672e706e67
68747470733a2f2f7777772e6461746f636d732d6173736574732e636f6d2f34383239342f313636303839383638362d6d61642d6f6e626f617264696e672d392d696d706163742e706e673f6175746f3d666f726d6174

### PR DESCRIPTION
**Pull request by jaivsh**
## Adding Introslider and Onboarding for new users!

Closes #89 

## Description

I've added onboarding and intro slider for first-time users, which would make them familiar with the usability of the app and it's features. This also includes creation of the suitable graphic images and other secondary stuff. For this, i've used the following packages from pub.dev:

intro_slider
shared_preferences
IsFirstRun

## Screenshots
Screenshot_20230704_231703

Screenshot_20230704_231736
Screenshot_20230704_231723

Screenshot_20230704_231822

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by jaivsh** [comment]
Hi @m0hit-kumar can you please review this PR? Thanks!

**Review by jaivsh — COMMENTED** [review]
Removed unnessary swift files, which were causing the runchecks to fail.

**Comment by jaivsh** [comment]
Hi @m0hit-kumar I've removed all swift files, which were causing the tests to fail. Hence, can you please check them again?

**Comment by jaivsh** [comment]
Hi @m0hit-kumar I've recently chcked with the GSSOC team: the way in which your codeql is designed is wrong. The codeql has identified c++ and swift as your project's primary languages, which is not correct. Your project is based in flutter, so Dart turns out to be your primary language. Hence, the codeql should be set up in dart, and not in cpp or swift. This is the reason why it is failing those checks. in the PR. Hence, I'd require please review it. Thanks!

**Comment by m0hit-kumar** [comment]
> Hi @m0hit-kumar I've recently chcked with the GSSOC team: the way in which your codeql is designed is wrong. The codeql has identified c++ and swift as your project's primary languages, which is not correct. Your project is based in flutter, so Dart turns out to be your primary language. Hence, the codeql should be set up in dart, and not in cpp or swift. This is the reason why it is failing those checks. in the PR. Hence, I'd require please review it. Thanks!

i see that, do one thing resolve the conflicts and I will merge your PR

**Comment by jaivsh** [comment]
@m0hit-kumar resolved conflicts, please merge!

**Pull request merged**
