### PR TITLE
Whole UI  updated -GSSOC23

### PR DESCRIPTION
**Pull request by yagnik2411**
**### 1] UI updated pages**

1.  admin signup page
2. admin complete profile page
3. Menu page
4. clients board page
5. admin dashboard
6. admin otp page
7. admin login page
8.  admin generates qr code page

 using  ### _new illustration and new colour pallet_

### CODE REVIEW

**Comment by m0hit-kumar** [comment]
can you put the SS of what you have changed in the ui

**Comment by yagnik2411** [comment]
It is here,
Ss of ui

**Comment by yagnik2411** [comment]
can you merge it plEASE?

**Comment by yagnik2411** [comment]
> can you merge it plEASE?

@m0hit-kumar

**Comment by yagnik2411** [comment]
Sir please merge it,so I get points.

**Comment by m0hit-kumar** [comment]
> Sir please merge it,so I get points.

your pr has conflict with the main resolve it first , I have added necessary tag

**Comment by yagnik2411** [comment]
Sir,I resolved my PR conflict so merge it as soon as possible so I get points

**Comment by yagnik2411** [comment]
sir why closed this request ?

**Pull request closed without merging**
